### ISSUE TITLE
Homework error after deadline

### ISSUE THREAD

**Issue by tc-imba** [joint-online-judge/cb4#10]
When entering a problem in a homework after ddl, an error occurs:

Traceback (most recent call last):
  File "/home/liu/oj/cb4/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/home/liu/oj/cb4/venv/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/home/liu/oj/cb4/vj4/handler/base.py", line 224, in __iter__
    yield from super(Handler, self).__iter__()
  File "/home/liu/oj/cb4/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 657, in __iter__
    resp = yield from method()
  File "/home/liu/oj/cb4/vj4/handler/contest.py", line 354, in get
    page_title=pdoc['title'], path_components=path_components)
  File "/home/liu/oj/cb4/vj4/handler/base.py", line 251, in render
    self.response.text = self.render_html(template_name, **kwargs)
  File "/home/liu/oj/cb4/vj4/handler/base.py", line 199, in render_html
    return template.Environment().get_template(template_name).render(kwargs)
  File "/home/liu/oj/cb4/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/liu/oj/cb4/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/liu/oj/cb4/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liu/oj/cb4/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/liu/oj/cb4/vj4/ui/templates/problem_detail.html", line 1, in top-level template code
    {% extends "layout/basic.html" %}
  File "/home/liu/oj/cb4/vj4/ui/templates/layout/basic.html", line 2, in top-level template code
    {% extends "layout/html5.html" %}
  File "/home/liu/oj/cb4/vj4/ui/templates/layout/html5.html", line 36, in top-level template code
    {% block body %}{% endblock %}
  File "/home/liu/oj/cb4/vj4/ui/templates/layout/basic.html", line 12, in block "body"
    {% block content %}{% endblock %}
  File "/home/liu/oj/cb4/vj4/ui/templates/problem_detail.html", line 54, in block "content"
    {% include "partials/problem_sidebar.html" %}
  File "/home/liu/oj/cb4/vj4/ui/templates/partials/problem_sidebar.html", line 8, in top-level template code
    {% include "partials/problem_sidebar_homework.html" %}
  File "/home/liu/oj/cb4/vj4/ui/templates/partials/problem_sidebar_homework.html", line 10, in top-level template code
    {% if handler.is_ongoing(tdoc) or handler.is_extend(tdoc) %}
jinja2.exceptions.UndefinedError: 'vj4.handler.contest.ContestDetailProblemHandler object' has no attribute 'is_extend'

**Comment by tc-imba** [comment]
may discover the definition and usage of is_extend to solve this

**Comment by zzhou612** [comment]
fix: typo in handler is_homework_extended
